### ISSUE TITLE
https://www.facebook.com/laine.rondinaii

### ISSUE THREAD

**Issue by pambec** [santoshvijapure/DS_with_hacktoberfest#169]
# Please follow the checklist:

- [ ] Did you [add your name](https://github.com/santoshvijapure/DS_with_hacktoberfest#1-add-your-name)?
- [ ] Did you add the [profile page](https://github.com/santoshvijapure/DS_with_hacktoberfest#2-add-a-profile-page)?
- [ ] Did you [create a vanilla version of your favourite data structure](https://github.com/santoshvijapure/DS_with_hacktoberfest#3-create-vanilla-version-of-your-favourite-data-structure-in-your-favouite-language)?

### Bug reports:

Please replace this line with a brief summary of your issue **AND** if reporting a build issue include the link from.

### Features:

**Please note by far the quickest way to get a new feature is to file a [Pull Request](https://github.com/santoshvijapure/DS_with_hacktoberfest/pulls).**

We will consider your request but it may be closed if it's something we're not actively planning to work on.
